Serialization and consistency fixes.
allscale/allscale_api pull request #11
Opened 2017-10-23 15:04 UTC by sithhell

- StaticGridFragment and GridFragment should both have getTotalSize()
 - Implementing serialization for StaticGrid andFragment and GridFragment

2017-10-23 15:14 UTC, HerbertJordan requested changes

2017-10-23 15:14 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Can't the more general insert and extract interface used instead? This would avoid creating unnecessary instances.

2017-10-23 15:14 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/static_grid.h
> +		static StaticGridFragment load(utils::ArchiveReader& reader) {
Same her

2017-10-23 19:33 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Why should it? We can return a fragment directly from an HPX action (for example here: https://github.com/allscale/allscale_runtime/blob/develop/allscale/components/data_item.hpp#L351). I'd rather mark the `insert` and `extract` functions as redundant. They are currently not needed by the DIM since we never explicitly serialize the fragments.

2017-10-23 19:39 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Also, by using the `extract` interface, we always copy at least twice: Fragment->vector (potential copy for wire transfer) vector->Fragment. By using the serialization, we Avoid the first and second copy completely. Without zero copy, we have Fragment -> wire data -> Fragment.

2017-10-24 07:39 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
The `extract` and `insert` function enable the direct serialization of sub-sets of covered data (e.g. ghost cells) of a given fragment, while a full serialization as you propose only allows to serialize all or nothing.

For instance, if you have a fragment covering [100,200) and you only need to extract the elements [100,110), as computed by a transfer plan, you can do so with the `extract` by passing the given range. With the serialization you do not have this flexibility.

The implementation of `load` and `store` as provided by you can be implemented easily through `insert` and `extract`, but not the other way arround.

Regarding your second comment: both functions work directly on ArchiveReader / Writer streams. All optimizations that are thus present for serialization should be valid for those too. I do not see where the extra-copy comes into play. `extract` and `insert` do not produce temporary vectors.

2017-10-24 07:46 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
As in the [code](https://github.com/allscale/allscale_runtime/blob/develop/allscale/components/data_item.hpp#L351-L363) I linked earlier, only a subset is being returned. I don't have direct access to the archives that are used during serialization. Unless I create an extra view object or similar.

`extract` and `insert` are then not usable when transferring fragments (which might contain only a subset of data). Having a `load` and `store` is needed for exactly this use case.

2017-10-24 07:53 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
The problem with an extra view object is that I have to temporarily construct a fragment with the contents on the receiving end anyways. I could get rid of one extra copy of the fragment data. This doesn't mean that the proposed addition isn't needed after all.

2017-10-24 07:53 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
But in this code you are the one creating unnecessary copies by creating this temporary fragment.

The leanest way should be somewhat like this:
```
Archive transfer(hpx::id_type const& id, region_type const& region)
{
    std::unique_lock<mutex_type> l(mtx_);

    auto store_it = store.find(id);
    HPX_ASSERT(store_it != store.end());
    ArchiveWriter writer;
    store_it->second.fragment.extract(writer,region);
    return writer.to_archive();
}
```
and on the receiver side
```
store_it->second.fragment.insert(ArchiveReader(src->transfere(id,region)));
```
or similar.

Can you "pipe" serialization streams directly between locations with low overhead?

2017-10-24 08:00 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
An `Archive` is not serializable. In any case, such a view object could be created which does something similar for that specific use case. For creating backups however, this is unnecessary boilerplate.

What you miss is that we have to go over the wire, a simple line like `src->transfer(id, region)` doesn't just return `Archive` verbatim. All return values and function parameters are being serialized transparently if the operation is remote.

The proposed addition is absolutely needed.

2017-10-24 08:15 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
No, I get that you have to go over the wire. The presented code should be considered more like pseudo code.

Ideally there would be some sort of streaming API to transfer data through the serialization process, in addition to the implicit parameter serialization process. But based on your statements, I guess there is no such thing.

Thus, what I'd suggest is to make such an "Archive" type a universal view object which is cheap to transfer. An archive is likely a simply byte array to be transfered. The current temporary fragment based solution requires a lot more structure to be build up and destructed. Especially in cases like ipic3d where the cell objects are complex, composed of multiple std::vector instances or even trees.

2017-10-24 08:17 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
If it helps, don't call it Archive but e.g. MarshalledObject or PackedObject instead ...

2017-10-24 08:47 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
So what? This argument is derailing. My point remains that having this additional feature is needed. Be at least for API symmetry.

2017-10-24 09:05 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
I don't see how it is needed and why this additional requirement should be imposed on Data Item developers. 

If you need this for real, it can be done generic using the existing `extract` and `insert` interface without any lose of flexibility.

2017-10-24 09:47 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
As said, the flexibility loss is by not allowing those objects to be arguments or return values from actions. Using `insert` or `extract` for that just increases boilerplate and clutters the code there.

But whatever.

2017-10-24 11:34 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
I don't want always to be the one opposing suggestions and shortcuts. But the foundation of many of those design decisions is based on essential concepts important for the overall design that need to be preserved -- unless, of cause, a flaw is discovered.

In this particular instance it is the case that data fragments themselves do not have value semantic (in the general case). They can't be copied or moved, unlike e.g. regions or the data values stored within their cells. Generally, fragments can not be passed by value as arguments or return values, and should thus also not be supported as such for remote calls. 

For me it is problematic to that making such non-value objects serializable since this implies the possiblity of creating copies -- through the serialization process.

It is important to not get to focused on grids here. Grids are a convenient special case. However, with mesh fragments providing value semantic will be much tougher, implying significant performance impacts if this will really be required.

2017-10-24 13:53 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
In this case the design is indeed flawed. Sometimes, copies are indeed semantically needed, sometimes. One particular case is the backup, or replication, which is by definition a copy of the original item.
From a semantic point of view, if everything that is contained in a specific object has value semantics, there is nothing wrong with the object having value semantics as well.
Besides, serialization isn't necessarily a copy operation. In the context of HPX action calls, it is indeed closer to a copy operation.

What is the rationale that the fragments/facades are non-copyable and non-movable? Is there anything besides possible inefficiency?

N.B.: a combination of extract and insert can indeed be seen as a copy operation, while not expressed with a copy constructor or copy assignment, the result is still a copy.

2017-10-24 20:03 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
We do not allow users to copy Data Items (facades) due to the complexity this would impose on management overhead. In the runtime, the copy would have to receive a new I'd and location information needs to be duplicated -- and from that moment on managed independently. The semantic of copy-constructors and assignment operations would have to be strictly enforced -- something that can not be tested with e.g. meta-programming -- and those operations would also have to be intercepted by the compiler to implant corresponding runtime calls.

By making them non-copyable we stay clear of that difficulties for the scope of the current project since it is not required by any of the pilots. But you are right, in principle it could be added. However, currently something like this is not foreseen. And it would take lots of unnecessary engineering effort for next to no gain when it comes to publications.

Data Item instances are currently to be thought of like global data structures, created at startup and shut down at the end -- for simplicity. 

For the fragments: all the user-visible content of those is copy-able, but there might be additional management structures they are maintaining. For instance, they may be bound to some memory-mapped file (like it will be for the meshes). While this is still just a performance issue (all those can be created and closed whenever needed, or even managed by some singleton-manager) fragments are furthermore not stand-along constructs. For their construction they require in general some shared state associated to the data item they belong to. In case of the grid, this only contains the overall grid size, which is small and you can serialize it with the rest of the content, as covered in your implementation. However, for the mesh, this contains the entire topological data of the mesh, a partition tree describing the potential fragmentation of the mesh, as well as closure information associated to each partition, for each kind of node relation. Sending this around with the fragment is massive overhead in terms of data volume. And without this shared data block, no instance can be created.

Thus, actually serializing and de-serializing a fragment, including its shared data, leads to a duplication of the shared data that in principle would be OK, if it wouldn't cost performance, data transfer volume and potentially prohibitively high memory usage.

We should probably soon develop a manual example based on meshes ...

2017-10-25 10:10 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Well, in that case, the design is flawed for the following reasons:
1) It is influenced by upper layers, which should handle the limitations separately (in case of the runtime, copying data items is not a big deal).
2) Just because something might be inefficient doesn't mean it should be impossible
3) Implementation details of the concepts are being exposed
4) Since there is shared data among fragments, there is no reason why it should be copied in the first place. It is shared after all and a property of the container owning the fragments. As a matter of fact, this shared data is currently at least serializable for all implementations of the concept.

2017-10-25 10:50 UTC, sithhell commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Besides, the proposed patch is solely about the fragment, not the actual data item ...

2017-10-25 18:51 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Through this discussion I realized that we could raise the non-value-semantic restriction on Data Items. We could, for instance, bind the life-cycle of a facade object to some "Main-Data-Item-Reference" that has ownership on the shared data structure. When it is send through serialization, those references become "DataItemReferences" as we have them now, somewhat similar to the shared vs. weak pointer concept.

Regarding the fragments: my problem with making them serializable is that in the load-case all you have is an ArchiveReader to restore a Fragment instance, which in the general case needs to including a reference to a shared data instance. And here you only have two options: include the shared data in the Archive or use some side-channel. The latter is what is there now with the `extract` and `insert` interface, where you can create a fragment using the shared data (which is thus shared) and then fill in the serialized data from some source. The serialized data thus does not require to cover any shared data.

Anyway, if you want to realize additional features and take over the coordination with the API (Philipp) and the Compiler (both Peters) and the Analysis (me) I am fine with it. It is just that I already have way to much on my plate to consider major redesigns right now.

2017-10-25 18:53 UTC, HerbertJordan commented on code/api/include/allscale/api/user/data/grid.h
> +		static GridFragment load(utils::ArchiveReader& reader) {
Out of interest: Regarding your point 2) - How are implementation details exposed?

2018-03-07 11:22 UTC, closed without merging